### PR TITLE
Added new blog in md format about LLM

### PR DESCRIPTION
**Pull request by Ankush1oo8**
made a blog post about LLM and Attached a image with it

### CODE REVIEW

**Comment by ekrishnachaitanya2004** [comment]
Congratulations on the successful merge of your pull request! 🎉 Your contribution has made a valuable addition to the dev blog, and I appreciate your hard work and effort.

If you have any more ideas or projects in mind, feel free to share. Looking forward to collaborating more in the future!

**Comment by Ankush1oo8** [comment]
Thanks

**Comment by ekrishnachaitanya2004** [comment]
I wanted to let you know that I successfully merged your pull request—thank you for your contribution! However, I noticed that your name isn’t showing up as a contributor in the repository.

To ensure you get recognized for your work, could you double-check that your commits are linked to your GitHub account? If you used a different email address for your commits, it may not associate correctly.

**Comment by Ankush1oo8** [comment]
So what should I do now

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ankush1oo8** [comment]
what should i do my contribution is not being shown in contributors

**Comment by ekrishnachaitanya2004** [comment]
Contact me via [Discord](https://discord.gg/wmuGFyaNhttps://discord.gg/wmuGFyaN)

**Pull request merged**
