### PR TITLE
Add blog post

### PR DESCRIPTION
**Pull request by Ankush1oo8**
created a new blog post to teach about cyprocurrency

### CODE REVIEW

**Comment by ekrishnachaitanya2004** [comment]
I noticed you recently opened a pull request on the dev blog website but then closed it after a few hours. I wanted to check in and see if there were any issues or feedback you encountered during the process. If you’re still interested, I’d love for you to submit it again – your contribution would be greatly appreciated!

Please feel free to let me know if there’s anything I can do to support or if you have any questions about the PR.

Thanks for your interest in contributing, and hope to hear from you soon!

**Comment by Ankush1oo8** [comment]
Ok sir I will re-upload the file but it was showing me error in netlify logs and I was not able to resolve it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ekrishnachaitanya2004** [comment]
No worries about the error – it’s not a problem at all! Please feel free to re-upload the code, and if any issues come up again, I’ll take a look and make any necessary adjustments on my end.

**Comment by Ankush1oo8** [comment]
Thanks man

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
